name: Docker

on:
  push:
    branches:
      - Feature1

jobs:

  build:
    name: docker-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0
      - name: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: login-registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
                type=sha,format=short,prefix=,suffix=,lower=true
                type=sha,format=long,prefix=,suffix=,lower=true
                type=ref,event=branch,prefix=,suffix=,lower=true

      - name: build-and-push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          # labels: aymanelsayeed/test
          labels: ${{ steps.metadata.outputs.labels }}
          tags: |
                aymanelsayeed/${{ steps.metadata.outputs.tags }}:latest
