name: first

on: [push, pull_request, workflow_dispatch]

jobs:
  job1:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        uses: actions/checkout@v4.0.0
      - name: step-2
        run: env | sort

  job2:
    name: second-job
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        uses: actions/checkout@v4.0.0
      - name: step-2
        run: env | sort
